### ISSUE TITLE
Can't use version 2 in Xamarin.Forms

### ISSUE THREAD

**Issue by sundraw** [porrey/Solar-Calculator#4] opened 2019-03-25 12:54 UTC
I was successfully using version 1 of Solar Calculator in my Xamarin.Forms project, except that this package caused problems when I wanted to internationalise the app (so I had to delay i18n). Now I noticed that version 2 is available and hoped that i18n issue might be fixed in it. Unfortunately, my attempt to update the package failed with the following message:

> Could not install package 'SolarCalculator 2.0.4'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile78', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Is it possible to know what should I change to get this package installed?

Thanks!

**Comment by porrey** [comment] 2019-03-29 22:07
The library was converted to a .NET Standard library so that it is compatible with other platforms. I just successfully added the package to Visual Studio on my MacBook Pro. I was also able to add the package to a Xamarin application in Windows. if you could outline steps to reproduce your issue I could look at it more closely.

**Comment by porrey** [comment] 2020-01-19 03:04
Closing due to no more feedback.

**Closed** 2020-01-19 03:04 UTC
